update report summary test location
scanapi/scanapi pull request #479
Opened 2021-08-01 19:34 UTC by GitVitor

## Description
update report summary test location
update report classes following BEMCSS pattern
close unclosed html tags

## Motivation behind this PR?
[478](https://github.com/scanapi/scanapi/issues/478)

## What type of change is this?
Feature

## Checklist
 

- [ x ]  I have added a changelog entry / my PR does not need a new changelog entry. [Instructions](https://github.com/scanapi/scanapi/wiki/Changelog).
- [ ] I have added/updated unit tests. [Instructions](https://github.com/scanapi/scanapi/wiki/Writing-Tests).
- [ x ] New and existing unit tests pass locally with my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally#tests)
- [ ] I have self-documented code my changes by adding docstring(s) and comment(s). [Instructions](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes)
- [ x ] Current PR does not significantly decrease the code coverage and docstring coverage.
- [ x ] My code follows the style guidelines of this project.
- [ x ] I have run ScanAPI locally and manually tested my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally).

## Issue

Closes #<issue_number>

2021-08-02 20:48 UTC, camilamaia requested changes
Thank you very much for the contribution!!

I left just a minor suggestion related to the CHANGELOG. Otherwise everything is great ⭐️ This position is much better 🎨

2021-08-02 20:48 UTC, camilamaia commented on CHANGELOG.md
>  ### Fixed
```suggestion
### Changed
- Summary tests location to the top of the report [#479](https://github.com/scanapi/scanapi/pull/479)

### Fixed
```

2021-08-02 20:48 UTC, camilamaia commented on CHANGELOG.md
> +- Change summary tests location. [#479](https://github.com/scanapi/scanapi/pull/479)
```suggestion
```

2021-08-03 14:36 UTC, GitVitor commented
> Thank you very much for the contribution!!
> 
> I left just a minor suggestion related to the CHANGELOG. Otherwise everything is great ⭐️ This position is much better 🎨

Suggestion merged

2021-08-03 15:02 UTC, camilamaia approved these changes

2021-08-03 15:07 UTC, merged

2021-08-03 15:07 UTC, camilamaia commented
@GitVitor Congrats for your first PR merged! Thank you very much!

I am going to send you an invite to join the ScanAPI org on GitHub 🚀 We invite everyone that has contributed with a merged PR in any of our repos. Here you can check our [Contributing Guidelines](https://github.com/scanapi/contributors/blob/main/CONTRIBUTING.md) so you can understand better how it works.

And once again, thank you! 🙇‍♀️