Add a --browse option in CLI
scanapi/scanapi pull request #496
Opened 2021-08-13 20:26 UTC by renato04

## Description
I added a new option to open the report result on a browser.

## Motivation behind this PR?
Closes #465

## What type of change is this?

It is a new feature

## Checklist
 

- [x]  I have added a changelog entry / my PR does not need a new changelog entry. [Instructions](https://github.com/scanapi/scanapi/wiki/Changelog).
- [x] I have added/updated unit tests. [Instructions](https://github.com/scanapi/scanapi/wiki/Writing-Tests).
- [x] New and existing unit tests pass locally with my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally#tests)
- [x] I have self-documented code my changes by adding docstring(s) and comment(s). [Instructions](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes)
- [ ] Current PR does not significantly decrease the code coverage and docstring coverage.
- [x] My code follows the style guidelines of this project.
- [x] I have run ScanAPI locally and manually tested my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally).
- [x] I have squashed my commits. [Instructions](https://github.com/scanapi/scanapi/wiki/Squashing-Commits).

## Issue

Closes #465

2021-08-14 01:10 UTC, Pradhvan requested changes

2021-08-14 01:10 UTC, Pradhvan commented on scanapi/scan.py
> +    """Open the results file on a browser
@renato04 if it's one line doc string it's good if the closing quotes are ends on the same line. That way static analysis won't fail too. 😄

2021-08-14 01:10 UTC, Pradhvan commented on scanapi/settings.py
>          super(dict, self).__init__()
Can you update the super call? From `super(dict, self).__init__()`  -> `super().__init__()` that way I guess static analysis CI would pass.

2021-08-14 01:11 UTC, Pradhvan commented
@renato04 great job ⭐  Just left some minor comments for the static analysis to pass.

2021-08-14 02:29 UTC, renato04 commented
Thanks @Pradhvan I'll fix it as soon as possible

2021-08-16 12:58 UTC, renato04 commented
@Pradhvan I fixed it!

2021-08-16 13:15 UTC, Pradhvan approved these changes
LGTM 👍🏾  @camilamaia what do you think ?

2021-08-16 13:43 UTC, hebertjulio commented
Look good to me. Browser open with successful! :rocket: :smile:

2021-08-16 13:49 UTC, Pradhvan commented
> Look good to me. Browser open with successful! rocket smile

Great! Thanks @hebertjulio  for reviewing it. Feel free to approve the PR. 😄

2021-08-16 14:04 UTC, hebertjulio approved these changes

2021-08-16 15:15 UTC, merged