Adr2/update report html UI
scanapi/scanapi pull request #506
Opened 2021-09-09 02:05 UTC by GitVitor

## Description
UI change:
    1. add Gotham Font Family;
    2. Variables CSS with colors;
            2.1. Update red color to use: #f14668;
            2.2. Update green color to use: #48c78e;
    3. Add visual wrapper to following areas: request content, request response and request test;
    4. New endpoint status UI;
 
## Motivation behind this PR?
Following recent discussions on #161 we decide to implement new details to help users on visualize related request data.

## What type of change is this?
Feature

## Checklist

- [x]  I have added a changelog entry / my PR does not need a new changelog entry. [Instructions](https://github.com/scanapi/scanapi/wiki/Changelog).
- [ ] I have added/updated unit tests. [Instructions](https://github.com/scanapi/scanapi/wiki/Writing-Tests).
- [x] New and existing unit tests pass locally with my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally#tests)
- [ ] I have self-documented code my changes by adding docstring(s) and comment(s). [Instructions](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes)
- [x] Current PR does not significantly decrease the code coverage and docstring coverage.
- [x] My code follows the style guidelines of this project.
- [x] I have run ScanAPI locally and manually tested my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally).
- [x] I have squashed my commits. [Instructions](https://github.com/scanapi/scanapi/wiki/Squashing-Commits).

## Issue

 #161

2021-09-09 17:24 UTC, camilamaia commented
Hey, @GitVitor, thank you very much for the PR 🙌

I run the branch on my local machine and tested it using Chrome, Firefox, and Safari.

I made a circle in the improvements points I found. In Safari, there is some information missing, for example. There are other small issues related to alignment, space...

#### Chrome
Version 93.0.4577.63 (Official Build) (x86_64)

![Chrome](https://user-images.githubusercontent.com/2728804/132732605-653efc8a-99d5-4874-8b6e-f15e5a4d29ca.png)
![chrome-extended](https://user-images.githubusercontent.com/2728804/132732608-333de4b4-e0d9-4fd9-a72c-edd4c361d4bc.png)

#### Firefox
91.0 (64-bit)

![firefox](https://user-images.githubusercontent.com/2728804/132732616-382bf4cb-fb32-4f12-9411-849940be06f2.png)
![firefox-expanded](https://user-images.githubusercontent.com/2728804/132732611-6046c841-ce8b-4f31-bd80-ca941577cdce.png)

#### Safari
Version 14.1.2 (16611.3.10.1.6)

![safari](https://user-images.githubusercontent.com/2728804/132732621-7091aaad-284a-4612-a353-606042b42d4c.png)
![safari-expanded](https://user-images.githubusercontent.com/2728804/132732618-6cc363e8-a3d5-4f46-b177-eabf8287bc36.png)

2021-10-06 15:10 UTC, Pradhvan commented
@GitVitor hey 👋🏾  are you still working on this ?

2021-10-13 20:27 UTC, GitVitor commented
Hello folks, sorry i was busy in last month. I will work on this in next days.

2022-04-10 10:24 UTC, astenstrasser requested changes
Hi @GitVitor, thanks for the PR!
I run it locally and in chrome looks like somethings are not aligned, like status and tables.
I tried to check what was the problem but could not fix it. Can you take a look?
Thanks!!

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/16165682/162613703-13158cf3-1282-457c-a4fd-0033802c0fa6.png">

2022-04-10 10:37 UTC, astenstrasser commented on scanapi/templates/report.html
> +    <link href="http://fonts.cdnfonts.com/css/gotham" rel="stylesheet">
```suggestion
```

2022-04-10 10:37 UTC, astenstrasser commented on scanapi/templates/report.html
> +            font-family: 'Gotham', sans-serif;
```suggestion
            font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto,
                 "Helvetica Neue", Arial, sans-serif;
```

2022-04-10 10:40 UTC, astenstrasser approved these changes

2022-04-10 10:46 UTC, astenstrasser commented on CHANGELOG.md
> +-
```suggestion

```

2022-04-10 10:47 UTC, astenstrasser commented on CHANGELOG.md
>  ### Fixed
```suggestion

### Fixed
```

2022-04-10 10:56 UTC, merged