Fix/issue/512
scanapi/scanapi pull request #515
Opened 2021-09-28 14:03 UTC by shifqu

## Description
Enrich global context in eval calls in `CodeEvaluator._assert_code`

## Motivation behind this PR?
When writing an assert statement in scanapi which uses a list (or any other) comprehension, the code would fail.

## What type of change is this?
Bugfix

## Checklist
- [x]  I have added a changelog entry / my PR does not need a new changelog entry. [Instructions](https://github.com/scanapi/scanapi/wiki/Changelog).
- [x] I have added/updated unit tests. [Instructions](https://github.com/scanapi/scanapi/wiki/Writing-Tests).
- [x] New and existing unit tests pass locally with my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally#tests)
- [x] I have self-documented code my changes by adding docstring(s) and comment(s). [Instructions](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes)
- [x] Current PR does not significantly decrease the code coverage and docstring coverage.
- [x] My code follows the style guidelines of this project.
- [x] I have run ScanAPI locally and manually tested my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally).
- [x] I have squashed my commits. [Instructions](https://github.com/scanapi/scanapi/wiki/Squashing-Commits).

## Issue
Closes #512

2022-04-10 09:43 UTC, astenstrasser commented
Hey @shifqu, thanks for the PR. 
Looks great, nice approach :)

I notice there are some other commits included in the PR, not only your changed.
Could you please adjust it so we can merge?
Thanks!!

2022-04-10 09:43 UTC, astenstrasser requested changes
Hey @shifqu, thanks for the PR.
Looks great, nice approach :)

I notice there are some other commits included in the PR, not only your changed.
Could you please adjust it so we can merge?
Thanks!!

2022-05-27 14:32 UTC, shifqu commented
Requested changes have been pushed. I also squashed the commits

2022-05-30 09:14 UTC, camilamaia approved these changes

2022-05-30 11:58 UTC, astenstrasser approved these changes

2022-05-30 12:56 UTC, merged

2022-06-01 12:13 UTC, camilamaia commented
Congrats on your first merged PR! 🌟 Thank you very much!

I am going to send you an invite to join the ScanAPI org on GitHub 🚀 We invite everyone that has contributed with a merged PR in any of our repositories. Here you can check our [Contributing Guidelines](https://github.com/scanapi/contributors/blob/main/CONTRIBUTING.md) so you can understand better how it works.

Check your email/GitHub notifications to find the invite. If you accept it, you will also be able to clone directly our repositories, without needing to fork them. 

Welcome on board and once again, thank you! 🙇‍♀️